:toc:
:toc-title: Оглавление:


ДОБРО ПОЖАЛОВАТЬ В АД

= Укажите верную запись для обращения к нестатическому методу unit32_t экземпляр класса ОБЪЯВЛЕН КАК ADC MYADC

Ответ: myADC.getCode(1U);

= укажите верные утверждения для модуля ацп микроконтроллера

Ответ:
АЦП микроконтроллера может работать в сканнирующем режиме +
АЦП микроконтроллера имеет 16 каналов +
АЦП микроконтроллера последовательного приближения +

= укажите верный вариант запуска ацп микроконтроллера на преобразователь, пользоваться документацией на микроконтроллер

Ответ:ADC1::CR2::SWSTAR::On::Set();

= как правильно делать курсовую?

Ответ: Сделать анализ треований заранее, задать вопросы преподователю……(Но я бы выбрал про жирафика)


= укажите верные утверждания относящиеся к классам (не сильно уверен)
Ответ:

К публичному статистическому классу можно обратиться не создавая объект класса +
Публичные атрибуты доступны всем +
Класс можно наследовать от другого класса +
Нельзя создать объект абстрактного класса +
Конструктор необходим для инициализации атрибутов классс (это не точно) +

= укажите верные утверждения для микроконтроллера

Разработка ПО для микроконтроллера возможна на C++

Разработка ПО для микроконтроллера возможна на C

Разработка ПО для микроконтроллера возможна на Assembler


= укажите верные для модуля usart микроконтролера утверждения

В модуле может настроить размер данных (8 и 9) бит

Модуль может работать в режиме с 1 и 2 стоповыми битами

Модуль может работать в режиме проверки четности данных


= укажите верные утверждения для графического отображения uml

Наследование показывается линией с треугольником +
Интерфейс показывается в виде круга +
Композиция показывается линией с закраженым ромбом +
Агрегация показывается линией с незакрашенным ромбом +

= укажите верные утверждения для графического отображения классов в uml

Приватные атрибутов класса указываются с помощью –. +
Статические атрибуты класса указваются с помощью подчеркивания +
Виртуальные методы класса выделяются курсивом +
Публичные методы классов указываются с помощью +. +

= укажите выерные утверждения для отображения класса в uml

Виртуальные класс указывается наклонным шрифтом +
Константный атрибут класса указывается с помощью операции = или значения +

= укажите верную для задач осрв утверждения

Задача как правило имеет свой стек +
Задача как правило имеет приоритет  +
Задачу можно опросить +
Задачу можно заблокировать (перевести в режим ожидания) +

= укажите существующие возможности среды разработки iar. выберите один или несколько советов::

а. Существует возможность пошаговой отладки программ +
c. Существует возможность просмотра регистров микроконтроллера +
d. Существует возможность отслеживания выполнения задача Операционной Системы Реального Времени +
f. Существует возможность просмотра глобальных и локальных переменных +
g. Содержит компилятор языка программирования С +

= укажите возможные источники тактирования системной частоты для микроконтроллера stm32f411

a. Внутренний высокочастотный RC-генератор (HSI) +
b. Низкочастотный внутренний RC-генератор на на 32 кГц (LSI) +
e. Система ФАПЧ (PLL) +
g Внешний высокочастотный генератор(HSE) +
k. Низкочастотный внешний источник на 32,768 кГц(LSE) +

= Укажите верный вариант запуска АЦП микроконтроллера STM32F411 на преобразование регулярных каналов (можно пользоваться документацией на микроконтроллер)

ADC1::CR2::Swstart::On::Set() :

= какое число выведет программа?

std:: uint32_t* ptr = reinterpret_cast<std::uint32_f*>(0x40012000);
pir++;
std::cout << ptr<< std::endl;
Ответ: 0x40012004

= где располагаются локальные переменные?

Ответ: в регистрах или в стеке. (или в кадре стека)

= укажите верные утверждения, выберите один или несколько ответов:

b. Код разрабатывается на основе детальной архитектуры
d. Общая архитектура разрабатывается на основе анализа требований к ПО и необходима для понимания как будет работать
e. Перед разработкой модулей работы с периферией необходимо детально ознакомиться со спецификацией микроконтроллера

= укажите правильный порядок настройки модуля usart на передачу данных. выберите один или несколько ответов:

b. Настроить порты на альтернативную функции, настроить регистры состояния модуля, включить модуль, разрешить микроконтроллеру глобальное прерывание
c. Настроить порты на альтернативную функцию, подать тактирование на модуль, настроить скорость передачи, настроить

= когда уместно использовать static_cast приведение? выберите один или несколько ответов:

b. Для приведения указателя на void* к любому типу
c. Для приведения близких типов

= укажите верные типы регистров в микроконтроллере stm32f411, выберите один или несколько ответов:

a. Вспомогательные
d. Специальные
e. Оперативные

= как правильно присвоить новое значение (10) переменной "с" через указатель ptr, если он…

a. *ptr = 10;

= какие типы данных поддерживает компилятор c++ выберите один или несколько ответов:

b. С плавающей точкой
d. Структурные
f. Адресные
h. Целые

= укажите верную последовательность настройки таймера в режим работы как счетчика. выберите один ответ:

a. Подать тактирование,
•	Установить делитель частоты для таймера в регистре PSC
•	Установить источник генерации прерываний по событию переполнение с помощью бита URS в регистре CR1
•	Установить значение до которого счетчик будет считать в регистре перезагрузке ARR
•	Скинуть флаг генерации прерывания UIF по событию в регистре SR
•	Установить начальное значение счетчика в 0 в регистре CNT
•	Проверять пока не будет установлен флаг генерации прерывания по событию UIF в регистре SR
•	Как только флаг установлен остановить счетчик, сбросить бит EN в регистре CR1.
•	Сбросить флаг генерации прерывания UIF по событию в регистре SR

= назовите основные характеристики микроконтроллера stm32

128 кБайт ОЗУ +
Внутренний источник частоты 16 МГц +
Встроенное 12 разрядное 16 канальное АЦП +
32 разрядное ядро ARM Cortex M4 +
Встроенный DMA контроллер +
3 USART порта +

= укажите существующие возможности среды разработки iar

Содержит вомпилятор языка С++
Существует возможность отслеживания выполнения задач ОСРВ
Существует возможность просмотра регистров микроконтроллера
Существует возможность просмотра глобальных и локальных переменных
Существует возможность пошаговой отладки программ

= укажите верную запись для настройки порта ports ножки 12 на выход

|= (1 << 12)

= укажите верные утверждения для прерываний 

Маскируемые прерывания сложно запретить
Прерывания это сигнал сообщающий о наступлении какого-либо события от периферии
Прерывания могут быть немаскируемые
Прерывания бывают асинхронными
Вектор прерывания – номер прерывания

=  укажите верные утверждения для системы прерывания в микроконтроллере 

Обработчик прерываний можно написать самому
В таблице векторов прерываний хранится адрес обработчика прерываний
Большинство прерываний немаскируемые
Обработчик прерываний может быть один на несколько прерываний

= укажите верные утверждения для осрв

ОСВР позволяют упростить архитектуру сложных систем +
ОСВР бывают с вытесняющей многозадачностью +
ОСВР имеет планировщик +
ОСВР предназначена для обеспечения интерфейса к ресурсам критических по времени систем +
ОСВР с кооперативной многозадачностью (не уверена) +


= укажите средства межзадачной коммуникации

прерывания
события, 
очередь
триггер

= укажите правильную запись  очистки бита 6

MyVar &=~64 


= укажите правильную запись установки бита 3

MyVar |= (1<<3)

