:toc:
:toc-title: Оглавление:



= Укажите верную запись для обращения к нестатическому методу unit32_t экземпляр класса ОБЪЯВЛЕН КАК ADC MYADC

Ответ: myADC.getCode(1U);

= УКАЖИТЕ ВЕРНЫЕ УТВЕРЖДЕНИЯ ДЛЯ МОДУЛЯ АЦП МИКРОКОНТРОЛЛЕРА

Ответ:
АЦП микроконтроллера может работать в сканнирующем режиме
АЦП микроконтроллера имеет 16 каналов
АЦП микроконтроллера последовательного приближения

= УКАЖИТЕ ВЕРНЫЙ ВАРИАНТ ЗАПУСКА АЦП МИКРОКОНТРОЛЛЕРА НА ПРЕОБРАЗОВАТЕЛЬ, ПОЛЬЗОВАТЬСЯ документацией на микроконтроллер

Ответ:ADC1::CR2::SWSTAR::On::Set();

= КАК ПРАВИЛЬНО ДЕЛАТЬ КУРСОВУЮ?

Ответ: Сделать анализ треований заранее, задать вопросы преподователю……(Но я бы выбрал про жирафика)


= УКАЖИТЕ ВЕРНЫЕ УТВЕРЖДАНИЯ ОТНОСЯЩИЕСЯ К КЛАССАМ (НЕ СИЛЬНО УВЕРЕН)
Ответ:
К публичному статистическому классу можно обратиться не создавая объект класса
Публичные атрибуты доступны всем
Класс можно наследовать от другого класса
Нельзя создать объект абстрактного класса
Возможно еще про то что конструктора инициализирует атрибуты класса

= УКАЖИТЕ ВЕРНЫЕ УТВЕРЖДЕНИЯ ДЛЯ МИКРОКОНТРОЛЛЕРА

Разработка ПО для микроконтроллера возможна на C++
Разработка ПО для микроконтроллера возможна на C
Разработка ПО для микроконтроллера возможна на Assembler

= УКАЖИТЕ ВЕРНЫЕ ДЛЯ МОДУЛЯ USART МИКРОКОНТРОЛЕРА УТВЕРЖДЕНИЯ:

В модуле может настроить размер данных (8 и 9) бит
Модуль может работать в режиме с 1 и 2 стоповыми битами
Модуль может работать в режиме проверки четности данных

= УКАЖИТЕ ВЕРНЫЕ УТВЕРЖДЕНИЯ ДЛЯ ГРАФИЧЕСКОГО ОТОБРАЖЕНИЯ UML

Наследование показывается линией с треугольником
Композиция показывается линией с закраженым ромбом
Агрегация показывается линией с незакрашенным ромбом

= УКАЖИТЕ ВЕРНЫЕ УТВЕРЖДЕНИЯ ДЛЯ ГРАФИЧЕСКОГО ОТОБРАЖЕНИЯ КЛАССОВ В UML

Приватные атрибутов класса указываются с помощью –
Статические атрибуты класса указваются с помощью подчеркивания
Виртуальные методы класса выделяются курсивом
Публичные методы классов указываются с помощью +

= УКАЖИТЕ ВЫЕРНЫЕ УТВЕРЖДЕНИЯ ДЛЯ ОТОБРАЖЕНИЯ КЛАССА В UML

Виртуальные класс указывается наклонным шрифтом
Константный атрибут класса указывается с помощью операции = или значения

= УКАЖИТЕ ВЕРНУЮ ДЛЯ ЗАДАЧ ОСРВ УТВЕРЖДЕНИЯ

Задача как правило имеет свой стек
Задача как правило имеет приоритет
Задачу можно опросить
Задачу можно заблокировать (перевести в режим ожидания)

= УКАЖИТЕ СУЩЕСТВУЮЩИЕ ВОЗМОЖНОСТИ СРЕДЫ РАЗРАБОТКИ IAR. ВЫБЕРИТЕ ОДИН ИЛИ НЕСКОЛЬКО СОВЕТОВ:

а. Существует возможность пошаговой отладки программ
c. Существует возможность просмотра регистров микроконтроллера
d. Существует возможность отслеживания выполнения задача Операционной Системы Реального Времени
f. Существует возможность просмотра глобальных и локальных переменных
g. Содержит компилятор языка программирования С

= УКАЖИТЕ ВОЗМОЖНЫЕ ИСТОЧНИКИ ТАКТИРОВАНИЯ СИСТЕМНОЙ ЧАСТОТЫ ДЛЯ МИКРОКОНТРОЛЛЕРА STM32F411

a. Внутренний высокочастотный RC-генератор (HSI)
b. Низкочастотный внутренний RC-генератор на на 32 кГц (LSI)
e. Система ФАПЧ (PLL)
g Внешний высокочастотный генератор(HSE)
k. Низкочастотный внешний источник на 32,768 кГц(LSE)

= Укажите верный вариант запуска АЦП микроконтроллера STM32F411 на преобразование регулярных каналов (можно пользоваться документацией на микроконтроллер)

ADC1::CR2::Swstart::On::Set() :

= КАКОЕ ЧИСЛО ВЫВЕДЕТ ПРОГРАММА?

std:: uint32_t* ptr = reinterpret_cast<std::uint32_f*>(0x40012000);
pir++;
std::cout << ptr<< std::endl;
Ответ: 0x40012004

= ГДЕ РАСПОЛАГАЮТСЯ ЛОКАЛЬНЫЕ ПЕРЕМЕННЫЕ?

Ответ: в регистрах или в стеке. (или в кадре стека)

= УКАЖИТЕ ВЕРНЫЕ УТВЕРЖДЕНИЯ, ВЫБЕРИТЕ ОДИН ИЛИ НЕСКОЛЬКО ОТВЕТОВ:

b. Код разрабатывается на основе детальной архитектуры
d. Общая архитектура разрабатывается на основе анализа требований к ПО и необходима для понимания как будет работать
e. Перед разработкой модулей работы с периферией необходимо детально ознакомиться со спецификацией микроконтроллера

= УКАЖИТЕ ПРАВИЛЬНЫЙ ПОРЯДОК НАСТРОЙКИ МОДУЛЯ USART НА ПЕРЕДАЧУ ДАННЫХ. ВЫБЕРИТЕ ОДИН ИЛИ НЕСКОЛЬКО ОТВЕТОВ:

b. Настроить порты на альтернативную функции, настроить регистры состояния модуля, включить модуль, разрешить микроконтроллеру глобальное прерывание
c. Настроить порты на альтернативную функцию, подать тактирование на модуль, настроить скорость передачи, настроить

= КОГДА УМЕСТНО ИСПОЛЬЗОВАТЬ STATIC_CAST ПРИВЕДЕНИЕ? ВЫБЕРИТЕ ОДИН ИЛИ НЕСКОЛЬКО ОТВЕТОВ:

b. Для приведения указателя на void* к любому типу
c. Для приведения близких типов

= УКАЖИТЕ ВЕРНЫЕ ТИПЫ РЕГИСТРОВ В МИКРОКОНТРОЛЛЕРЕ STM32F411, ВЫБЕРИТЕ ОДИН ИЛИ НЕСКОЛЬКО ОТВЕТОВ:

a. Вспомогательные
d. Специальные
e. Оперативные

= КАК ПРАВИЛЬНО ПРИСВОИТЬ НОВОЕ ЗНАЧЕНИЕ (10) ПЕРЕМЕННОЙ "С" ЧЕРЕЗ УКАЗАТЕЛЬ PTR, ЕСЛИ ОН…

a. *ptr = 10;

= КАКИЕ ТИПЫ ДАННЫХ ПОДДЕРЖИВАЕТ КОМПИЛЯТОР C++ ВЫБЕРИТЕ ОДИН ИЛИ НЕСКОЛЬКО ОТВЕТОВ:

b. С плавающей точкой
с. Строковые
g. Комплексные
h. Целые

= УКАЖИТЕ ВЕРНУЮ ПОСЛЕДОВАТЕЛЬНОСТЬ НАСТРОЙКИ ТАЙМЕРА В РЕЖИМ РАБОТЫ КАК СЧЕТЧИКА. ВЫБЕРИТЕ ОДИН ОТВЕТ:

a. Подать тактирование,
•	Установить делитель частоты для таймера в регистре PSC
•	Установить источник генерации прерываний по событию переполнение с помощью бита URS в регистре CR1
•	Установить значение до которого счетчик будет считать в регистре перезагрузке ARR
•	Скинуть флаг генерации прерывания UIF по событию в регистре SR
•	Установить начальное значение счетчика в 0 в регистре CNT
•	Проверять пока не будет установлен флаг генерации прерывания по событию UIF в регистре SR
•	Как только флаг установлен остановить счетчик, сбросить бит EN в регистре CR1.
•	Сбросить флаг генерации прерывания UIF по событию в регистре SR

= НАЗОВИТЕ ОСНОВНЫЕ ХАРАКТЕРИСТИКИ МИКРОКОНТРОЛЛЕРА STM32

128 кБайт ОЗУ
Внутренний источник частоты 16 МГц
Встроенное 12 разрядное 16 канальное АЦП
32 разрядное ядро ARM Cortex M4
Встроенный DMA контроллер
3 USART порта

= УКАЖИТЕ СУЩЕСТВУЮЩИЕ ВОЗМОЖНОСТИ СРЕДЫ РАЗРАБОТКИ IAR

Содержит вомпилятор языка С++
Существует возможность отслеживания выполнения задач ОСРВ
Существует возможность просмотра регистров микроконтроллера
Существует возможность просмотра глобальных и локальных переменных
Существует возможность пошаговой отладки программ

= УКАЖИТЕ ВЕРНУЮ ЗАПИСЬ ДЛЯ НАСТРОЙКИ ПОРТА PORTS НОЖКИ 12 НА ВЫХОД


= УКАЖИТЕ ВЕРНЫЕ УТВЕРЖДЕНИЯ ДЛЯ ПРЕРЫВАНИЙ 

Маскируемые прерывания сложно запретить
Прерывания это сигнал сообщающий о наступлении какого-либо события от периферии
Прерывания могут быть немаскируемые
Прерывания бывают асинхронными
Вектор прерывания – номер прерывания

= УКАЖИТЕ ВЕРНЫЕ УТВЕРЖДЕНИЯ ДЛЯ СИСТЕМЫ ПРЕРЫВАНИЯ В МИКРОКОНТРОЛЛЕРЕ 

Обработчик прерываний можно написать самому
В таблице векторов прерываний хранится адрес обработчика прерываний
Большинство прерываний немаскируемые
Обработчик прерываний может быть один на несколько прерываний

= УКАЖИТЕ ВЕРНЫЕ УТВЕРЖДЕНИЯ ДЛЯ ОСРВ

ОСВР позволяют упростить архитектуру сложных систем
ОСВР бывают с вытесняющей многозадачностью
ОСВР бывают с совместной многозадачностью
ОСВР предназначена для обеспечения интерфейса к ресурсам критических по времени систем
ОСВР с кооперативной многозадачностью (не уверена)

= УКАЖИТЕ СРЕДСТВА МЕЖЗАДАЧНОЙ КОММУНИКАЦИИ

прерывания
события, 
очередь
триггер
нотификация

= УКАЖИТЕ ПРАВИЛЬНУЮ ЗАПИСЬ  ОЧИСТКИ БИТА 6

MyVar &=~64

= УКАЖИТЕ ПРАВИЛЬНУЮ ЗАПИСЬ УСТАНОВКИ БИТА 3

MyVar |= (1<<3)

